env:
  es2021: true
  node: true

parserOptions:
  ecmaVersion: 2021
  sourceType: module
  project: tsconfig.json

extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended

rules:
  no-multiple-empty-lines:
    - error
    - max: 1
  no-var:
    - error
  no-console:
    - warn
  arrow-parens:
    - error
    - always
  curly:
    - error
    - all
  no-else-return:
    - error
    - allowElseIf: false
  max-params:
    - error
    - 3
  object-curly-newline:
    - error
  lines-between-class-members:
    - error
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowTypedFunctionExpressions: true
  '@typescript-eslint/quotes':
    - error
    - single
  '@typescript-eslint/object-curly-spacing':
    - error
    - always
  '@typescript-eslint/semi':
    - error
    - always
  '@typescript-eslint/comma-dangle':
    - error
    - always-multiline
  '@typescript-eslint/no-use-before-define':
    - error
  '@typescript-eslint/no-unused-vars':
    - error
    - vars: all
      args: after-used
      argsIgnorePattern: ^_
      caughtErrors: all
  '@typescript-eslint/no-empty-interface':
    - error
    - allowSingleExtends: true
  '@typescript-eslint/no-misused-promises':
    - error
  '@typescript-eslint/padding-line-between-statements':
    - error
    - blankLine: always
      prev: '*'
      next:
        - switch
        - class
        - function
        - if
        - return
        - try
        - interface
        - type
  '@typescript-eslint/explicit-member-accessibility':
    - error
  '@typescript-eslint/no-explicit-any':
    - error
  import/no-unresolved:
    - off
  import/no-default-export:
    - error
  import/newline-after-import:
    - error
    - count: 1
  import/first:
    - error
  import/no-duplicates:
    - error
  import/group-exports:
    - error
  import/order:
    - error
    - newlines-between: always
      alphabetize:
        order: asc
      pathGroups:
        - pattern: '~/**'
          group: internal
      groups:
        - - builtin
          - external
        - internal
        - - parent
          - sibling
        - index
        - object
        - type
